### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Priyansh2** [clemfromspace/scrapy-selenium#14]
Tried with both pip and pip3. It shows Segmentation fault (core dumped) at end.
Here is the complete log `Collecting scrapy-selenium
  Using cached https://files.pythonhosted.org/packages/db/a1/bed5f1b668afe43fd51a545360ad0ac27580da13538fbdf9e8a03d831e9d/scrapy_selenium-0.0.5-py3-none-any.whl
Collecting selenium>=3.9.0 (from scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/b8/53/9cafbb616d20c7624ff31bcabd82e5cc9823206267664e68aa8acdde4629/selenium-3.14.0-py2.py3-none-any.whl
Collecting scrapy>=1.0.0 (from scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/5d/12/a6197eaf97385e96fd8ec56627749a6229a9b3178ad73866a0b1fb377379/Scrapy-1.5.1-py2.py3-none-any.whl
Collecting urllib3 (from selenium>=3.9.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting cssselect>=0.9 (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/7b/44/25b7283e50585f0b4156960691d951b05d061abf4a714078393e51929b30/cssselect-1.0.3-py2.py3-none-any.whl
Collecting service-identity (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/29/fa/995e364220979e577e7ca232440961db0bf996b6edaf586a7d1bd14d81f1/service_identity-17.0.0-py2.py3-none-any.whl
Collecting lxml (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/03/a4/9eea8035fc7c7670e5eab97f34ff2ef0ddd78a491bf96df5accedb0e63f5/lxml-4.2.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting pyOpenSSL (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl
Collecting w3lib>=1.17.0 (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/37/94/40c93ad0cadac0f8cb729e1668823c71532fd4a7361b141aec535acb68e3/w3lib-1.19.0-py2.py3-none-any.whl
Collecting six>=1.5.2 (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting PyDispatcher>=2.0.5 (from scrapy>=1.0.0->scrapy-selenium)
Collecting Twisted>=13.1.0 (from scrapy>=1.0.0->scrapy-selenium)
Collecting queuelib (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/4c/85/ae64e9145f39dd6d14f8af3fa809a270ef3729f3b90b3c0cf5aa242ab0d4/queuelib-1.5.0-py2.py3-none-any.whl
Collecting parsel>=1.1 (from scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/fd/1a/9642a5ea68763d5e7c419df0873073e54bb23d0a8897d3c78e146dd6f355/parsel-1.5.0-py2.py3-none-any.whl
Collecting attrs (from service-identity->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service-identity->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
Collecting pyasn1 (from service-identity->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Collecting cryptography>=2.2.1 (from pyOpenSSL->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/59/32/92cade62c645756a83598edf56289e9b19aae5370642a7ce690cd06bc72f/cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl
Collecting hyperlink>=17.1.1 (from Twisted>=13.1.0->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/a7/b6/84d0c863ff81e8e7de87cff3bd8fd8f1054c227ce09af1b679a8b17a9274/hyperlink-18.0.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0 (from Twisted>=13.1.0->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted>=13.1.0->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting zope.interface>=4.4.2 (from Twisted>=13.1.0->scrapy>=1.0.0->scrapy-selenium)
Collecting constantly>=15.1 (from Twisted>=13.1.0->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted>=13.1.0->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/a3/86/14c16bb98a5a3542ed8fed5d74fb064a902de3bdd98d6584b34553353c45/Automat-0.7.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography>=2.2.1->pyOpenSSL->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=2.2.1->pyOpenSSL->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.7 (from cryptography>=2.2.1->pyOpenSSL->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting setuptools (from PyHamcrest>=1.9.0->Twisted>=13.1.0->scrapy>=1.0.0->scrapy-selenium)
  Using cached https://files.pythonhosted.org/packages/27/f9/0d705bb4963ee952946670f8a185d8ce3afca11084d60cf5c589622bfe6b/setuptools-40.3.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyOpenSSL->scrapy>=1.0.0->scrapy-selenium)
Installing collected packages: urllib3, selenium, cssselect, idna, asn1crypto, pycparser, cffi, six, cryptography, pyOpenSSL, attrs, pyasn1, pyasn1-modules, service-identity, lxml, w3lib, PyDispatcher, hyperlink, setuptools, PyHamcrest, incremental, zope.interface, constantly, Automat, Twisted, queuelib, parsel, scrapy, scrapy-selenium
Successfully installed Automat-0.7.0 PyDispatcher-2.0.5 PyHamcrest-1.9.0 Twisted-18.7.0 asn1crypto-0.24.0 attrs-18.2.0 cffi-1.11.5 constantly-15.1.0 cryptography-2.3.1 cssselect-1.0.3 hyperlink-18.0.0 idna-2.7 incremental-17.5.0 lxml-4.2.5 parsel-1.5.0 pyOpenSSL-18.0.0 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycparser-2.18 queuelib-1.5.0 scrapy-1.5.1 scrapy-selenium-0.0.5 selenium-3.14.0 service-identity-17.0.0 setuptools-40.3.0 six-1.11.0 urllib3-1.23 w3lib-1.19.0 zope.interface-4.5.0
Segmentation fault (core dumped)`

**Comment by clemfromspace** [comment]
Hi @Priyansh2, I don't really think this error is related directly to the `scrapy-selenium` package, as you are the first to have this issue. I suggest to have a look at [this stackoverlow question](https://stackoverflow.com/questions/13654449/error-segmentation-fault-core-dumped) and maybe try to investigate your Python installation first.
