### ISSUE TITLE
Example spiders

### ISSUE THREAD

**Issue by amirasyraf** [clemfromspace/scrapy-selenium#17]
Hi, would you happen to have any simple spider examples? I've read the 'Usage' section, but still not sure how to implement it along with parsing detail pages.

For example, would the following be correct?

```
from rumahmy.items import PropwallItem
import scrapy

class PropwallSpider(scrapy.Spider):
    name = 'propwallspider'
    allowed_domains = ['www.propwall.my']
    start_urls = ['https://www.propwall.my/classifieds?listing=For+Rent&state=&category=&tenure=&furnishing=&blurb=&price_min=&price_max=&bedroom_min=&bedroom_max=&bathroom_min=&bathroom_max=&built_up_size_min=&built_up_size_max=&filter_id=&filter_type=&sort=&page=%s&keyword=' % page for page in range(1,2)]

    def parse(self, response):
        yield SeleniumRequest(url, self.parse_result)

    def parse_result(self, response):
        for listing in listings:
            #Parse items here

            yield scrapy.Request(link,meta={'PropwallItem': PropwallItem},callback=self.parse_detail_page)

    def parse_detail_page(self, response):
        # Parse detail page here

        yield PropwallItem
```

How do I get the Selenium response to **parse_detail_page**?

**Comment by clemfromspace** [comment]
Regarding the Spider example you provided, if you want to only use Selenium for the requests:

```python
from rumahmy.items import PropwallItem
import scrapy

class PropwallSpider(scrapy.Spider):
    name = 'propwallspider'
    allowed_domains = ['www.propwall.my']
    
    def start_requests(self):
         for page in range(1,2):
             yield SeleniumRequest(
                 url=f'https://www.propwall.my/classifieds?listing=For+Rent&state=&category=&tenure=&furnishing=&blurb=&price_min=&price_max=&bedroom_min=&bedroom_max=&bathroom_min=&bathroom_max=&built_up_size_min=&built_up_size_max=&filter_id=&filter_type=&sort=&page={page}%s&keyword=',
                 callback=self.parse_results
             )

    def parse_result(self, response):
        for listing in listings:
            #Parse items here
```

**Comment by amirasyraf** [comment]
Hi, thanks for your response.

How would I pass item between functions? 
With Scrapy `Request`, I can do the following, using the meta argument to pass item:

`yield scrapy.Request(link,meta={'PropwallItem': PropwallItem},callback=self.parse_detail_page)`

If I understand correctly, since `SeleniumRequest` is a subclass of Scrapy `Request`, I can just use the same argument for `SeleniumRequest`?

For example, passing item to a `parse_detail_page` function:

`yield SeleniumRequest(link,meta={'PropwallItem': PropwallItem},callback=self.parse_detail_page)`

And then in `parse_detail_page` function:

```python
def parse_detail_page(self, response):
        PropwallItem= response.meta.get('PropwallItem', {})
        #Parse items here
```
Would the above be correct?

**Comment by clemfromspace** [comment]
Hi @amirasyraf ,

Sorry for the late answer, yeah, the above example should work!
