### ISSUE TITLE
Suggestion: driver.execute_script

### ISSUE THREAD

**Issue by j4n7** [clemfromspace/scrapy-selenium#18]
Hi,

First of all, thanks for making this, I was getting a headacke trying to use scrapy + splash. This solution is much better, the only thing I'm missing is an option to execute custom javascript code. Right now I solved this using class inheritance, but it would be great if you can integrate it into the main program.

```
middlewares.py

class CustomSeleniumMiddleware(SeleniumMiddleware):

    def __init__(self, driver_name, driver_executable_path, driver_arguments):
        super().__init__(driver_name, driver_executable_path, driver_arguments)
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

settings.py

DOWNLOADER_MIDDLEWARES = {
    'xxx.middlewares.CustomSeleniumMiddleware': 800
}

```

**Comment by clemfromspace** [comment]
Hi @j4n7 ,

Thanks for your feedback!
If I understand correctly, you want to be able to pass a `execute_script` argument to the `SeleniumRequest`, like the following:

```python
yield SeleniumRequest(url, execute_script="window.scrollTo(0, document.body.scrollHeight);")
```

Does that sound good?

**Comment by j4n7** [comment]
Hi @clemfromspace,

Thanks for your answer.
Yes, that is what I mean, I have already implented a solution that resembles your example. When I have time I can send you a pull request. The change to the original code was minimal. 

What I am having more trouble is to implement a "proxy" parameter too, like:

`yield SeleniumRequest(url, execute_script="window.scrollTo(0, document.body.scrollHeight);", proxy="https://85.196.152.253:4674")`

Maybe you have some toughts about that.

Cheers!

**Comment by clemfromspace** [comment]
Hi @j4n7 ,

I will then wait your PR for the `execute_script` param :)

Regarding the `proxy` param, correct me if I'm wrong, but I don't think it should be passed to the `SeleniumRequest` but instead added to the `SETTINGS`:

```python
SELENIUM_DRIVER_NAME='firefox'
# other settings...
SELENIUM_DRIVER_PROXY={}  # You proxy settings
```

So you don't have to pass it on every `SeleniumRequest` you do.

WDYT?

**Comment by j4n7** [comment]
Well,

I think that is probably enough for most cases, but sometimes (as I do) yo will need a different proxy setting for each spider. For example, there are some websites you can only access from a certain country and you will need different proxies for that. That is whay I have come up with the idea of making a proxy parameter in SeleniumRequest.

The problem I see is that the Middleware class initializes the driver before executing the _from_crawler method. So if you create a proxy parameter in SeleniumRequest you would have to initialize the driver again, because as far as I know the Selenium Driver class only accepts the proxy parameter the moment it is initialized.

Excuse me if I'm a wrong, I'm just and amateur programmer and very new to Selenium.

Cheers.

**Comment by eyusupov** [comment]
I was also looking for a way to pass the script with the request, but then figured out that the same can be done in the Spider code with
```
response.meta['driver'].execute_script("window.scrollTo(0, document.body.scrollHeight);")
```
