### ISSUE TITLE
missing 1 required positional argument: 'url'

### ISSUE THREAD

**Issue by 1quintana** [clemfromspace/scrapy-selenium#20]
Hello I followed the installation guide, but I am having the next error. I am using python 3.7.0

```
    yield SeleniumRequest(url, self.parse)
  File "/usr/local/lib/python3.7/site-packages/scrapy_selenium/http.py", line 29, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'url'
```
I added  to the settings the next configuration

```
from shutil import which
SELENIUM_DRIVER_NAME='chrome'
SELENIUM_DRIVER_EXECUTABLE_PATH=which('geckodriver')
SELENIUM_DRIVER_ARGUMENTS=['-headless']  # '--headless' if using chrome instead of firefox
```

here is my code
```
def start_requests(self):
      url = "http://egov.sos.state.or.us/br/pkg_web_name_srch_inq.do_name_srch?p_name=aa&p_regist_nbr=&p_srch=PHASE3P&p_print=FALSE&p_entity_status=ACTINA"
      yield SeleniumRequest(url, self.parse)

def parse(self, response):
   rows = response.selector.xpath("//table/tbody/tr")
```

One more tip, if I use the next way to implement selenium is working with no problem.
```
chromedriver = os.getcwd()+'/leadsScraper/chromedriver'
driver = webdriver.Chrome(chromedriver)
delay = 10
```

**Comment by clemfromspace** [comment]
Hi @1quintana ,

It looks like a difference between `SeleniumRequest` and the Scrapy `Request` classes.
This way, it should work (passing explicitly the `url` parameter):

```python
def start_requests(self):
      url = "http://egov.sos.state.or.us/br/pkg_web_name_srch_inq.do_name_srch?p_name=aa&p_regist_nbr=&p_srch=PHASE3P&p_print=FALSE&p_entity_status=ACTINA"
      yield SeleniumRequest(url=url, self.parse) # Here pass url=url instead of just url
```

I will open an issue to fix this thing, thank for your feedback.

**Comment by 1quintana** [comment]
Hello @clemfromspace 

Thank you so much for the fast answer. It did work good with your solution.

**Comment by wzyboy** [comment]
Hi @clemfromspace ,

I have encountered this as well. Passing `url` as kw arg instead of positional arg _does_ suppress the error, but it seems that the request is no longer processed by the middleware at all: trying to access `response.meta['driver']` raises `KeyError` now.

The browser still opens, but no tabs would open, no webpages would be navigated to, while the console output continues and the crawling goes on without the processing of the middleware.

**Comment by wrightwriter** [comment]
Still have this problem
