### ISSUE TITLE
meta data not in sync with driver

### ISSUE THREAD

**Issue by danmsf** [clemfromspace/scrapy-selenium#21]
Hi,
I'm running into a problem where the Meta data not in sync with current response.meta['driver'].
Specifically, Im looping over a list of id's which are part of a URL passed to the SeleniumRequest url 
I save the results and the id that is saved is  further down the list than the driver's output (the driver is lagging behind).

It seems the problem is in the first few ids, and then the lag persists...

Minimal example:

class ListSpider(scrapy.Spider):
    name = 'list_spider'
    custom_settings = {
        'LOG_LEVEL': 'ERROR',
        'LOG_ENABLED': True,
        'LOG_STDOUT': True,
        'CONCURRENT_REQUESTS':1,
        'USER_AGENT': 'Mozilla/5.0'
    }

    def __init__(self):
        scrapy.Spider.__init__(self)
        pydispatch.dispatcher.connect(self.handle_spider_closed, signals.spider_closed)

    def start_requests(self):

        urls = [
            'https://www.amazon.com'
        ]

		ids = ['B01C1E62P4','B00VGNBQSK','B074XXTCD2','B003YFI0O6']
        for id in ids:
            yield SeleniumRequest(
                    url='https://www.amazon.com/gp/offer-listing/' + id + '/?f_new=true',
                    callback=self.parse_result,
                    meta={
                        'id': id
                    }
            )
    
    def parse_result(self, response):
        url_asin = response.meta['driver'].current_url
        current_id  = url_id.replace('https://www.amazon.com/gp/offer-listing/','').replace('/?f_new=true','')
	    print(current_id,  response.meta['id'])
	    item = {}
	    item['id'] = response.meta['id']
       # and alot more parsing and logic :)
        yield item

    def handle_spider_closed(self, spider):
        work_time = datetime.now() - spider.started_on

I'm running on Windows 10x64

**Comment by clemfromspace** [comment]
Hi @danmsf,

Thanks for opening this,
Since it looks similar to #22 , I will close this one and let the discussion continue on the other issue.
