### ISSUE TITLE
infinite recursion when used together with scrapy.pipelines.images.ImagesPipeline

### ISSUE THREAD

**Issue by cyruszhang** [clemfromspace/scrapy-selenium#3]
`        if not isinstance(request, SeleniumRequest):
            return request`

should be changed to:

`        if not isinstance(request, SeleniumRequest):
            return`

when return None, the pipeline will move on; otherwise the request will be resceduled again and again, resulting in infinite loop

**Comment by clemfromspace** [comment]
Hi @cyruszhang, you are completely right, I will fix this ASAP.

**Comment by clemfromspace** [comment]
Closed via #8
