### ISSUE TITLE
How good is it with the session management?

### ISSUE THREAD

**Issue by gerosalesc** [clemfromspace/scrapy-selenium#4]
Let's say I logged into a site using Scrapy and then the spider crawls its way into a page where I  need Selenium for rendering, Would I still have to log into the site yet again to complete the request successfully? OR will it share Cookies and session information with the browser?

**Comment by clemfromspace** [comment]
hi @gerosalesc,

First of all, sorry for the really late answer.
About your question, you can look at the code here: https://github.com/clemfromspace/scrapy-selenium/blob/develop/scrapy_selenium/middlewares.py#L80

It's really basic, the middleware just pass along the cookies names/values from Scrapy to Selenium.
