### ISSUE TITLE
SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set

### ISSUE THREAD

**Issue by kc1** [clemfromspace/scrapy-selenium#42]
[![enter image description here][1]][1]

I'm trying out a scrapy package https://github.com/clemfromspace/scrapy-selenium. 

I've followed the directions on the main github page above. I started a new scrapy project and created a spider:

    from scrapy_selenium import SeleniumRequest

    from shutil import which

    SELENIUM_DRIVER_NAME = 'firefox'

    SELENIUM_DRIVER_EXECUTABLE_PATH = which('geckodriver')
    SELENIUM_DRIVER_ARGUMENTS=['-headless']  # '--headless' if using chrome instead of firefox

    class MySpider(scrapy.Spider):

        start_urls = ["http://yahoo.com"]
        name = 'test'

        def start_requests(self):
            for url in self.start_urls:
     
                yield SeleniumRequest(url, self.parse_index_page)

        def parse_index_page(self, response):
            ....

I've downloaded the latest geckodriver and set the path as above

The output contains:

     'scrapy.extensions.telnet.TelnetConsole',
     'scrapy.extensions.logstats.LogStats']
    2019-07-05 14:14:44 [scrapy.middleware] WARNING: Disabled SeleniumMiddleware: SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set
    2019-07-05 14:14:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
    2019-07-05 14:56:59 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
  

I don't see the selenium downloader and I see 

    WARNING: Disabled SeleniumMiddleware: SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set. 

What am I doing wrong?

  [1]: https://i.stack.imgur.com/ReDSA.jpg

**Comment by NinelieAimer** [comment]
You may not set environment variables, you should add the geckodriver.exe to the environment variables.As for me, I just move geckodriver.ext to the Python Scripts file.

**Comment by NinelieAimer** [comment]
> [![enter image description here](https://camo.githubusercontent.com/9868f5e7cd42a79f203510cccde4aacbe22e1832/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f52654453412e6a7067)](https://i.stack.imgur.com/ReDSA.jpg)
> 
> I'm trying out a scrapy package https://github.com/clemfromspace/scrapy-selenium.
> 
> I've followed the directions on the main github page above. I started a new scrapy project and created a spider:
> 
> ```
> from scrapy_selenium import SeleniumRequest
> 
> from shutil import which
> 
> SELENIUM_DRIVER_NAME = 'firefox'
> 
> SELENIUM_DRIVER_EXECUTABLE_PATH = which('geckodriver')
> SELENIUM_DRIVER_ARGUMENTS=['-headless']  # '--headless' if using chrome instead of firefox
> 
> 
> 
> class MySpider(scrapy.Spider):
> 
>     start_urls = ["http://yahoo.com"]
>     name = 'test'
> 
> 
>     def start_requests(self):
>         for url in self.start_urls:
>  
>             yield SeleniumRequest(url, self.parse_index_page)
> 
> 
>     def parse_index_page(self, response):
>         ....
> ```
> 
> I've downloaded the latest geckodriver and set the path as above
> 
> The output contains:
> 
> ```
>  'scrapy.extensions.telnet.TelnetConsole',
>  'scrapy.extensions.logstats.LogStats']
> 2019-07-05 14:14:44 [scrapy.middleware] WARNING: Disabled SeleniumMiddleware: SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set
> 2019-07-05 14:14:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
> 2019-07-05 14:56:59 [scrapy.middleware] INFO: Enabled downloader middlewares:
> ```
> 
> ['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
> 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
> 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
> 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
> 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
> 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
> 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
> 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
> 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
> 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
> 'scrapy.downloadermiddlewares.stats.DownloaderStats']
> 
> I don't see the selenium downloader and I see
> 
> ```
> WARNING: Disabled SeleniumMiddleware: SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set. 
> ```
> 
> What am I doing wrong?

You may not set environment variables, you should add the geckodriver.exe to the environment variables.As for me, I just move geckodriver.ext to the Python Scripts file.

**Comment by NinelieAimer** [comment]
> [![enter image description here](https://camo.githubusercontent.com/9868f5e7cd42a79f203510cccde4aacbe22e1832/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f52654453412e6a7067)](https://i.stack.imgur.com/ReDSA.jpg)
> 
> I'm trying out a scrapy package https://github.com/clemfromspace/scrapy-selenium.
> 
> I've followed the directions on the main github page above. I started a new scrapy project and created a spider:
> 
> ```
> from scrapy_selenium import SeleniumRequest
> 
> from shutil import which
> 
> SELENIUM_DRIVER_NAME = 'firefox'
> 
> SELENIUM_DRIVER_EXECUTABLE_PATH = which('geckodriver')
> SELENIUM_DRIVER_ARGUMENTS=['-headless']  # '--headless' if using chrome instead of firefox
> 
> 
> 
> class MySpider(scrapy.Spider):
> 
>     start_urls = ["http://yahoo.com"]
>     name = 'test'
> 
> 
>     def start_requests(self):
>         for url in self.start_urls:
>  
>             yield SeleniumRequest(url, self.parse_index_page)
> 
> 
>     def parse_index_page(self, response):
>         ....
> ```
> 
> I've downloaded the latest geckodriver and set the path as above
> 
> The output contains:
> 
> ```
>  'scrapy.extensions.telnet.TelnetConsole',
>  'scrapy.extensions.logstats.LogStats']
> 2019-07-05 14:14:44 [scrapy.middleware] WARNING: Disabled SeleniumMiddleware: SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set
> 2019-07-05 14:14:44 [scrapy.middleware] INFO: Enabled downloader middlewares:
> 2019-07-05 14:56:59 [scrapy.middleware] INFO: Enabled downloader middlewares:
> ```
> 
> ['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
> 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
> 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
> 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
> 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
> 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
> 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
> 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
> 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
> 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
> 'scrapy.downloadermiddlewares.stats.DownloaderStats']
> 
> I don't see the selenium downloader and I see
> 
> ```
> WARNING: Disabled SeleniumMiddleware: SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set. 
> ```
> 
> What am I doing wrong?

You may not set environment variables, you should add the geckodriver.exe to the environment variables.As for me, I just move geckodriver.exe to the Python Scripts file.

**Comment by Lincoln123** [comment]
Have same issue, don't understand why.
In settings.py I activeted middleware, and set:

from shutil import which
SELENIUM_DRIVER_NAME = 'firefox'
SELENIUM_DRIVER_EXECUTABLE_PATH = which('geckodriver')
SELENIUM_DRIVER_ARGUMENTS = ['-headless']
 when I run spider recieve :
SELENIUM_DRIVER_NAME and SELENIUM_DRIVER_EXECUTABLE_PATH must be set

**Comment by kaspars-gailitis** [comment]
I have the same issue, the settings are set in settings.py, but it shows the error.
I overcame it by appending the settings to the command

`scrapy crawl baseCrawler -s SELENIUM_DRIVER_NAME='firefox' -s SELENIUM_DRIVER_EXECUTABLE_PATH='{your/path/to/geckodriver}'`

**Comment by clemfromspace** [comment]
If you type `which geckodriver` in your terminal do you actually have the full path to the geckodriver?

**Comment by kaspars-gailitis** [comment]
Looks like I had some issues with the driver, I had to reinstall it using brew `brew install geckodriver` which seems to have fixed the issue, using the settings.py file works correctly now. I think the previous driver I had downloaded was not signed, have had some issues with PATH and executables since I updated to the latest Mac OS.

**Comment by clemfromspace** [comment]
Glad it solved :)

**Comment by dsouksavatd** [comment]
> Looks like I had some issues with the driver, I had to reinstall it using brew `brew install geckodriver` which seems to have fixed the issue, using the settings.py file works correctly now. I think the previous driver I had downloaded was not signed, have had some issues with PATH and executables since I updated to the latest Mac OS.

you saved my day :)
