### ISSUE TITLE
Can‘t work for specific URL

### ISSUE THREAD

**Issue by ChengZ95** [clemfromspace/scrapy-selenium#44]

**Comment by Chuck-ZC** [comment]
I can't get the xpath of the article titles on the URL: "https://www.toutiao.com/ch/news_game/".

**Comment by FredRF** [comment]
Hi Cheng,
You can look [here](https://docs.scrapy.org/en/latest/topics/selectors.html) for more information on xpath selectors.

However, for your case, your title would be obtained by:

```response.xpath('//a[@class="link title"]/text()').extract() ```

This will return a list of titles.
