### ISSUE TITLE
Install with pip in python 2.7

### ISSUE THREAD

**Issue by Noixas** [clemfromspace/scrapy-selenium#6]
I have tried upgrading pip and other libraries but still get this error, when I install it in python 3.x it worked 

> C:\Users\userName>pip install scrapy-selenium
> Collecting scrapy-selenium
>   Using cached https://files.pythonhosted.org/packages/af/05/99ededa143dc4e55cb31dc526d341ec38982eba2de93f19bef290b9b3779/scrapy-selenium-0.0.3.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "c:\users\userName\appdata\local\temp\pip-install-9yhlty\scrapy-selenium\setup.py", line 4, in <module>
>         from pip.download import PipSession
>     ImportError: No module named download
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in c:\users\userName\appdata\local\temp\pip-install-9yhlty\scrapy-selenium\

**Comment by leon0707** [comment]
This package won't work with pip 10. You have to downgrade your pip.

`pip install -U 'pip>=9,<10'`

**Comment by clemfromspace** [comment]
Hi @Noixas, this package is currently only compatible with Python 3.
