### ISSUE TITLE
How I Can Set Cookie

### ISSUE THREAD

**Issue by mustfkeskin** [clemfromspace/scrapy-selenium#62]
How i can load my cookies

1)Firstly I dump my cookies
driver = selenium.webdriver.Firefox()
driver.get("http://www.google.com")
pickle.dump( driver.get_cookies() , open("cookies.pkl","wb"))

2) Then i want to load like this
How i can communicate selenium and scrapy
cookies = pickle.load(open("cookies.pkl", "rb"))
for cookie in cookies:
    driver.add_cookie(cookie)

**Comment by Apuyuseng** [comment]
`https://github.com/clemfromspace/scrapy-selenium/blob/develop/scrapy_selenium/middlewares.py`
line 105

**Comment by demisx** [comment]
Clickable link for the above: https://github.com/clemfromspace/scrapy-selenium/blob/develop/scrapy_selenium/middlewares.py#L105

**Comment by mustfkeskin** [comment]
Hello I try insert my code but 
But i got this error: " object has no attribute 'driver'

```
def start_requests(self):

        cookies = pickle.load(open("utilities/pickles/chrome_cookies.pkl", "rb"))
        for cookie in cookies:
            for cookie_name, cookie_value in cookie.items():
                self.driver.add_cookie(
                    {
                        'name': cookie_name,
                        'value': cookie_value
                    }
                )
```

**Comment by mustfkeskin** [comment]
Now its work thank you
```
cookies = pickle.load(open("utilities/pickles/chrome_cookies.pkl", "rb"))
for cookie in cookies:
    response.request.meta['driver'].add_cookie(cookie)
```
