### ISSUE TITLE
How to change User-Agent?

### ISSUE THREAD

**Issue by Noman-Aziz** [clemfromspace/scrapy-selenium#75]
As the title says, how to change user-agent in scrapy-selenium?

**Comment by ohld** [comment]
So what was the solution? If I specify USER_AGENT in settings.py - It doesn't work.

**Comment by Noman-Aziz** [comment]
I didn't find any, i stopped using scrapy-selenium since it caused many issues apart from this,

**Comment by ohld** [comment]
@Noman-Aziz thanks. What was your alternative? Do you still use scrapy?

**Comment by Noman-Aziz** [comment]
I use Selenium for JavaScript sites (basically i extract the urls of required products using selenium and scrape them using scrapy afterwards).
